// +build !ignore_autogenerated

/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisClusterProviderSpec) DeepCopyInto(out *GenesisClusterProviderSpec) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisClusterProviderSpec.
func (in *GenesisClusterProviderSpec) DeepCopy() *GenesisClusterProviderSpec {
	if in == nil {
		return nil
	}
	out := new(GenesisClusterProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GenesisClusterProviderSpec) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisClusterProviderSpecList) DeepCopyInto(out *GenesisClusterProviderSpecList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GenesisClusterProviderSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisClusterProviderSpecList.
func (in *GenesisClusterProviderSpecList) DeepCopy() *GenesisClusterProviderSpecList {
	if in == nil {
		return nil
	}
	out := new(GenesisClusterProviderSpecList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GenesisClusterProviderSpecList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisClusterProviderSpecSpec) DeepCopyInto(out *GenesisClusterProviderSpecSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisClusterProviderSpecSpec.
func (in *GenesisClusterProviderSpecSpec) DeepCopy() *GenesisClusterProviderSpecSpec {
	if in == nil {
		return nil
	}
	out := new(GenesisClusterProviderSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisClusterProviderSpecStatus) DeepCopyInto(out *GenesisClusterProviderSpecStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisClusterProviderSpecStatus.
func (in *GenesisClusterProviderSpecStatus) DeepCopy() *GenesisClusterProviderSpecStatus {
	if in == nil {
		return nil
	}
	out := new(GenesisClusterProviderSpecStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisClusterProviderStatus) DeepCopyInto(out *GenesisClusterProviderStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisClusterProviderStatus.
func (in *GenesisClusterProviderStatus) DeepCopy() *GenesisClusterProviderStatus {
	if in == nil {
		return nil
	}
	out := new(GenesisClusterProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GenesisClusterProviderStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisClusterProviderStatusList) DeepCopyInto(out *GenesisClusterProviderStatusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GenesisClusterProviderStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisClusterProviderStatusList.
func (in *GenesisClusterProviderStatusList) DeepCopy() *GenesisClusterProviderStatusList {
	if in == nil {
		return nil
	}
	out := new(GenesisClusterProviderStatusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GenesisClusterProviderStatusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisClusterProviderStatusSpec) DeepCopyInto(out *GenesisClusterProviderStatusSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisClusterProviderStatusSpec.
func (in *GenesisClusterProviderStatusSpec) DeepCopy() *GenesisClusterProviderStatusSpec {
	if in == nil {
		return nil
	}
	out := new(GenesisClusterProviderStatusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisClusterProviderStatusStatus) DeepCopyInto(out *GenesisClusterProviderStatusStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisClusterProviderStatusStatus.
func (in *GenesisClusterProviderStatusStatus) DeepCopy() *GenesisClusterProviderStatusStatus {
	if in == nil {
		return nil
	}
	out := new(GenesisClusterProviderStatusStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisMachineProviderSpec) DeepCopyInto(out *GenesisMachineProviderSpec) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisMachineProviderSpec.
func (in *GenesisMachineProviderSpec) DeepCopy() *GenesisMachineProviderSpec {
	if in == nil {
		return nil
	}
	out := new(GenesisMachineProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GenesisMachineProviderSpec) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisMachineProviderSpecList) DeepCopyInto(out *GenesisMachineProviderSpecList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GenesisMachineProviderSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisMachineProviderSpecList.
func (in *GenesisMachineProviderSpecList) DeepCopy() *GenesisMachineProviderSpecList {
	if in == nil {
		return nil
	}
	out := new(GenesisMachineProviderSpecList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GenesisMachineProviderSpecList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisMachineProviderSpecSpec) DeepCopyInto(out *GenesisMachineProviderSpecSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisMachineProviderSpecSpec.
func (in *GenesisMachineProviderSpecSpec) DeepCopy() *GenesisMachineProviderSpecSpec {
	if in == nil {
		return nil
	}
	out := new(GenesisMachineProviderSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisMachineProviderSpecStatus) DeepCopyInto(out *GenesisMachineProviderSpecStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisMachineProviderSpecStatus.
func (in *GenesisMachineProviderSpecStatus) DeepCopy() *GenesisMachineProviderSpecStatus {
	if in == nil {
		return nil
	}
	out := new(GenesisMachineProviderSpecStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisMachineProviderStatus) DeepCopyInto(out *GenesisMachineProviderStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisMachineProviderStatus.
func (in *GenesisMachineProviderStatus) DeepCopy() *GenesisMachineProviderStatus {
	if in == nil {
		return nil
	}
	out := new(GenesisMachineProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GenesisMachineProviderStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisMachineProviderStatusList) DeepCopyInto(out *GenesisMachineProviderStatusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GenesisMachineProviderStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisMachineProviderStatusList.
func (in *GenesisMachineProviderStatusList) DeepCopy() *GenesisMachineProviderStatusList {
	if in == nil {
		return nil
	}
	out := new(GenesisMachineProviderStatusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GenesisMachineProviderStatusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisMachineProviderStatusSpec) DeepCopyInto(out *GenesisMachineProviderStatusSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisMachineProviderStatusSpec.
func (in *GenesisMachineProviderStatusSpec) DeepCopy() *GenesisMachineProviderStatusSpec {
	if in == nil {
		return nil
	}
	out := new(GenesisMachineProviderStatusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisMachineProviderStatusStatus) DeepCopyInto(out *GenesisMachineProviderStatusStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisMachineProviderStatusStatus.
func (in *GenesisMachineProviderStatusStatus) DeepCopy() *GenesisMachineProviderStatusStatus {
	if in == nil {
		return nil
	}
	out := new(GenesisMachineProviderStatusStatus)
	in.DeepCopyInto(out)
	return out
}
